kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.19.7
  extraMounts:
  - hostPath: /etc/localtime
    containerPath: /etc/localtime
  extraPortMappings:
  - containerPort: 30881
    hostPort: 9090